### ISSUE TITLE
snapraid config diff location with OMV 6.2 plugin

### ISSUE THREAD

**Issue by d4g79** [auanasgheps/snapraid-aio-script#54]
Hi,

OMV 6 with Snapraid 6.2 plugin

The old location for the snapraid.conf is @ etc/snapraid.conf

New location is @ etc/snapraid/omv-snapraid-88f2fa6e-f7f8-4258-82f6-be63f6d90259.conf

thats my config, not sure what thenumbers mean. To overcome this i had to rename the above file to snapraid.conf and place it ion the etc folder.

Script then works as normal. This is even the case if i try to run the snapraid sync under cli it searches etc for the config., In the OMV plugin GUI it works as expected.

Thanks

**Comment by auanasgheps** [comment]
Hi, can you please clarify the issue?

**Comment by d4g79** [comment]
With the new OMV6 plugin snapraid 6.2.1 there config location location is @ etc/snapraid but the scirpt is looking for the config at etc. 

thats the issue.

**Comment by auanasgheps** [comment]
I can see [this change](https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-snapraid/commit/a71699ed1d5c52d439a0b38bd724841a2089f2bb#diff-ec51a0700f76690197d8d1435d9401e03eaebf8bcdb847112e0a78b93bd88b1e) made to their script, which will either look for the location you mentioned or the original.

Looks like it's a change specific to multiple arrays. Is this your case?

Both in my test and production server, snapraid config is in `/etc/snapraid.conf`.

**Comment by auanasgheps** [comment]
Hi @d4g79 since I do not have multiple arrays (please confirm if this is your case) it's not easy for me to replicate this behavior.

Do not rename files generated by OMV, they could go back to the original name at some point in time, e.g. after an update.

The proper way to address this scenario is to change [this line](https://github.com/auanasgheps/snapraid-aio-script/blob/d968577f58cbf370ed1e3ffa054358b78d72598d/script-config.sh#L209) to point to your configuration file.

I could build an integrated way to read the config file, but it might not be worth the effort.
